wechat_pay:
    path: /wechat/pay/submit
    defaults: { _controller: '\Controller\WeChat\PayController::payAction'}

wechat_pay_token:
    path: /wechat/test/token
    defaults: { _controller: '\Controller\WeChat\PayController::getTokenAction'}

wechat_pay_return:
    path: /wechat/test/return
    defaults: { _controller: '\Controller\WeChat\PayController::payReturnAction'}

wechat_pay_warning:
    path: /wechat/pay/warning
    defaults: { _controller: '\Controller\WeChat\PayController::warningAction'}

wechat_pay_complaints:
    path: /wechat/pay/complaints
    defaults: { _controller: '\Controller\WeChat\PayController::complaintsAction'}